[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_contract = "FrE1dW61BTde2RNUgtR4euwB8wjDW8Fe4oWcVMgvcmVc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ritikbhatt020/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
